### ISSUE TITLE
[IMG]: 136 crashes and fails to come up

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#164]

**Comment by llelectronics** [comment]
Updating with sudo apt-get update && sudo apt-get upgrade fixes this via adb shell. 
Seems to be some library mismatch or too old on this build

**Comment by star-buck** [comment]
doesnt work here, upgrade is stuck at:
"Installing new version of config file /etc/init/bluetooth.conf ..."

**Comment by star-buck** [comment]
dpkg --reconfigure is then stuck at:
Setting up bluez (5.23-1ubuntu1~mtrudel1build1) ...

**Comment by star-buck** [comment]
@jriddell : Let's do a new IMG.

**Comment by llelectronics** [comment]
Yeah star-buck you are right. I forgot to mention it. 
I just added exit 0 to the postinst Script of bluez as it kept on hanging because of something in it. 
After that it worked though. 

A new image should fix it altogether I guess.

**Comment by star-buck** [comment]
@llelectronics :
even then much stuff on IMG 136 is borked:
camera doesnt work, muon dicsover still doesnt come up, still 3x okular icons on applauncher, none of the .click apps pe-installed, etc.

@jriddell :
Please see that tickets get solved and packages added.
I dont know if the initial 2.0GB of 2.0GB used limitation for 7-root partition after flashing is hindering the inclusion of new packages though?

**Comment by jriddell** [comment]
new image is up now in kubuntu-mobile/devel
